import { Category, Product } from './types';

const COFFEE_TABLE_IMAGE_WOOD =
  'https://images.unsplash.com/photo-1461418126083-a84e9ca935de?auto=format&fit=crop&w=800&q=80';
const COFFEE_TABLE_IMAGE_GLASS =
  'https://images.unsplash.com/photo-1718049719673-70ee6f6dfa28?auto=format&fit=crop&w=800&q=80';
const COFFEE_TABLE_IMAGE_MARBLE =
  'https://images.unsplash.com/photo-1718049719548-f5cea9f78592?auto=format&fit=crop&w=800&q=80';
const COFFEE_TABLE_IMAGE_TERRAZZO =
  'https://images.unsplash.com/photo-1714926340157-dd3a67e7b2c4?auto=format&fit=crop&w=800&q=80';
const COFFEE_TABLE_IMAGE_SIDE =
  'https://unsplash.com/photos/RVzwpzgiAIg/download?force=true&w=800';

export const CATEGORIES: Category[] = [
  {
    id: 'mattress',
    name: '床墊',
    description: '專業支撐，舒適入眠',
    image: '/images/mattress_double_1779274923685.png',
  },
  {
    id: 'sofas',
    name: '沙發',
    description: '居家生活的放鬆核心',
    image: '/images/living_room_inspiration_1779274975609.png',
  },
  {
    id: 'chairs',
    name: '椅子與餐椅',
    description: '兼具美感與人體工學',
    image: '/images/nordic_chair_white_bg_1779277500873.png',
  },
  {
    id: 'coffee-tables',
    name: '茶几與邊桌',
    description: '客廳美學的靈魂角色',
    image: COFFEE_TABLE_IMAGE_GLASS,
  },
  {
    id: 'dining-tables',
    name: '餐桌',
    description: '相聚時光的溫潤陪伴',
    image: '/images/dining_table_white_bg_1779277518370.png',
  },
  {
    id: 'lighting',
    name: '燈具',
    description: '氣氛與光影的完美調和',
    image: '/images/lighting_pendant_lamp.jpg',
  },
  {
    id: 'desks',
    name: '書桌與辦公',
    description: '激發靈感的創意空間',
    image: '/images/desk_workspace_modern.jpg',
  },
  {
    id: 'storage',
    name: '衣櫃與收納',
    description: '秩序感的北歐收納哲學',
    image: '/images/wardrobe_white_closet.jpg',
  },
  {
    id: 'rugs',
    name: '地毯',
    description: '腳尖上的柔軟觸感',
    image: '/images/nordic_rug_white_bg_1779277550962.png',
  },
  {
    id: 'decor',
    name: '家飾配件',
    description: '點亮空間的驚喜細節',
    image: '/images/minimalist_vase_white_bg_1779277533786.png',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'm3',
    name: 'HOVÅG 獨立筒彈簧床墊',
    categoryId: 'mattress',
    price: 15900,
    description: '高密度獨立筒搭配天然乳膠層，極致舒適體驗。',
    image: '/images/mattress_double_1779274923685.png',
    details: ['頂級睡感', '天然乳膠透氣層', '高密度彈簧'],
    specs: [
      { label: '尺寸', value: '180x200 公分 (雙人加大)' },
      { label: '材質', value: '獨立筒彈簧 + 乳膠' },
      { label: '軟硬度', value: '適中偏軟' },
    ],
    stock: [{ location: '內湖店', status: 'in-stock' }],
    tags: ['頂級', '乳膠'],
    sizeDisplay: '雙人加大',
    material: '獨立筒彈簧',
    aiReason: '',
  },
  {
    id: 'm2',
    name: 'ÅKREHAMN 泡棉床墊',
    categoryId: 'mattress',
    price: 12900,
    description: '三層不同密度的泡棉，提供溫和的支撐感。',
    image: '/images/mattress_double_new.jpg',
    details: ['絕佳支撐感', '適合偏好泡棉質感者', '易於拆洗床罩'],
    specs: [
      { label: '尺寸', value: '150x200 公分 (雙人)' },
      { label: '材質', value: '高彈性泡棉' },
      { label: '軟硬度', value: '適中' },
    ],
    stock: [{ location: '內湖店', status: 'low-stock' }],
    tags: ['泡棉', '絕佳支撐'],
    sizeDisplay: '雙人',
    material: '泡棉',
    aiReason: '',
  },
  {
    id: 'm5',
    name: 'VESTERÖY 獨立筒彈簧床墊',
    categoryId: 'mattress',
    price: 6990,
    description: '中價位獨立筒床墊，單人尺寸，適合學生或單身貴族。',
    image: '/images/mattress_single.jpg',
    details: ['適合單人使用', '獨立筒減少干擾', '偏硬支撐'],
    specs: [
      { label: '尺寸', value: '90x200 公分 (單人)' },
      { label: '材質', value: '獨立筒彈簧' },
      { label: '軟硬度', value: '偏硬' },
    ],
    stock: [{ location: '內湖店', status: 'in-stock' }],
    tags: ['獨立筒', '單人'],
    sizeDisplay: '單人',
    material: '獨立筒彈簧',
    aiReason: '',
  },
  {
    id: 'm4',
    name: 'MINNESUND 泡棉床墊',
    categoryId: 'mattress',
    price: 3490,
    description: '入門款泡棉床墊，適合預算有限的小資族。',
    image: '/images/mattress_single.jpg',
    details: ['經濟實惠', '輕量好搬運', '適合客房使用'],
    specs: [
      { label: '尺寸', value: '90x200 公分 (單人)' },
      { label: '材質', value: '聚氨酯泡棉' },
      { label: '軟硬度', value: '偏硬' },
    ],
    stock: [{ location: '內湖店', status: 'in-stock' }],
    tags: ['入門款', '小資'],
    sizeDisplay: '單人',
    material: '泡棉',
    aiReason: '',
  },
  {
    id: 'm9',
    name: 'DUNVIK 乳膠獨立筒床墊',
    categoryId: 'mattress',
    price: 18900,
    description: '頂級乳膠加獨立筒組合，雙人尺寸的極致睡眠。',
    image: '/images/mattress_closeup.jpg',
    details: ['頂級配置', '天然乳膠', '零干擾獨立筒'],
    specs: [
      { label: '尺寸', value: '150x200 公分 (雙人)' },
      { label: '材質', value: '乳膠 + 獨立筒彈簧' },
      { label: '軟硬度', value: '偏軟' },
    ],
    stock: [{ location: '內湖店', status: 'in-stock' }],
    tags: ['頂級', '乳膠'],
    sizeDisplay: '雙人',
    material: '獨立筒彈簧',
    aiReason: '',
  },
  {
    id: 'm1',
    name: 'VALEVÅG 獨立筒彈簧床墊',
    categoryId: 'mattress',
    price: 8900,
    description: '這張獨立筒彈簧床墊能為身體提供絕佳支撐，讓你整晚舒心好眠。',
    image: '/images/mattress_double_1779274923685.png',
    details: [
      '適合雙人使用',
      '偏硬支撐',
      '獨立筒彈簧，減少翻身干擾',
    ],
    specs: [
      { label: '尺寸', value: '150x200 公分 (雙人)' },
      { label: '材質', value: '鋼鐵, 聚氨酯泡棉' },
      { label: '軟硬度', value: '偏硬' },
    ],
    stock: [
      { location: '內湖店', status: 'in-stock' },
      { location: '新莊店', status: 'in-stock' },
    ],
    tags: ['偏硬支撐', '適合雙人'],
    sizeDisplay: '雙人',
    material: '獨立筒彈簧',
    aiReason: '',
  },
  {
    id: 'm6',
    name: 'MATRAND 記憶棉床墊',
    categoryId: 'mattress',
    price: 9900,
    description: '記憶棉材質完美貼合身型，釋放壓力點。',
    image: '/images/mattress_closeup.jpg',
    details: ['記憶棉貼合身型', '釋放肩頸壓力', '適合側睡者'],
    specs: [
      { label: '尺寸', value: '180x200 公分 (雙人加大)' },
      { label: '材質', value: '記憶棉' },
      { label: '軟硬度', value: '偏軟' },
    ],
    stock: [{ location: '內湖店', status: 'in-stock' }],
    tags: ['記憶棉', '側睡'],
    sizeDisplay: '雙人加大',
    material: '記憶棉',
    aiReason: '',
  },
  {
    id: 'm7',
    name: 'HYLLESTAD 獨立筒彈簧床墊',
    categoryId: 'mattress',
    price: 13900,
    description: '進階款獨立筒床墊，雙人加大尺寸，軟硬適中。',
    image: '/images/mattress_double_new.jpg',
    details: ['進階舒適', '加大尺寸', '透氣設計'],
    specs: [
      { label: '尺寸', value: '180x200 公分 (雙人加大)' },
      { label: '材質', value: '獨立筒彈簧' },
      { label: '軟硬度', value: '適中' },
    ],
    stock: [{ location: '內湖店', status: 'low-stock' }],
    tags: ['進階款', '加大'],
    sizeDisplay: '雙人加大',
    material: '獨立筒彈簧',
    aiReason: '',
  },
  {
    id: 'm8',
    name: 'MORGEDAL 泡棉床墊',
    categoryId: 'mattress',
    price: 4990,
    description: '中硬度泡棉床墊，單人尺寸，CP值極高。',
    image: '/images/mattress_single.jpg',
    details: ['CP值首選', '中硬度支撐', '適合學生族群'],
    specs: [
      { label: '尺寸', value: '90x200 公分 (單人)' },
      { label: '材質', value: '聚氨酯泡棉' },
      { label: '軟硬度', value: '適中' },
    ],
    stock: [{ location: '內湖店', status: 'in-stock' }],
    tags: ['CP值', '學生'],
    sizeDisplay: '單人',
    material: '泡棉',
    aiReason: '',
  },
  {
    id: 'c1',
    name: 'LACK 咖啡桌',
    categoryId: 'coffee-tables',
    price: 499,
    description: '天然木紋六角桌面，線條簡潔輕便，適合小型客廳空間。',
    image: COFFEE_TABLE_IMAGE_WOOD,
    details: [
      '天然木紋表面',
      '六角桌面造型',
      '易於組裝',
    ],
    specs: [
      { label: '尺寸', value: '90x55 公分' },
      { label: '材質', value: '木質貼皮' },
    ],
    stock: [
      { location: '網路商店', status: 'in-stock' },
      { location: '內湖店', status: 'in-stock', placementArea: '貨架 12, 走道 04' },
      { location: '新莊店', status: 'low-stock', placementArea: '貨架 08, 走道 02' },
      { location: '桃園店', status: 'out-of-stock', placementArea: '貨架 05, 走道 01' },
    ],
    tags: ['適合小客廳', '熱銷款'],
    variantTags: ['木紋色'],
    sizeDisplay: '中',
    material: '木質',
    aiReason: '木紋表面清晰，適合小客廳',
  },
  {
    id: 'c2',
    name: 'GLADOM 托盤桌',
    categoryId: 'coffee-tables',
    price: 399,
    description: '黑色金屬托盤式邊桌，附下層收納架，桌面可輕鬆搬移。',
    image: '/images/side_table_modern_1779274959832.png',
    details: [
      '黑色金屬框架',
      '托盤式桌面',
      '附下層置物架',
    ],
    specs: [
      { label: '尺寸', value: '45x53 公分' },
      { label: '材質', value: '鋼鐵, 環氧粉末塗料' },
    ],
    stock: [
      { location: '內湖店', status: 'in-stock' },
    ],
    tags: ['現代簡約', '多功能'],
    variantTags: ['黑色'],
    sizeDisplay: '小',
    material: '金屬',
    aiReason: '黑色托盤設計，輕型便利',
  },
  {
    id: 'c4',
    name: 'KRAGSTA 玻璃茶几',
    categoryId: 'coffee-tables',
    price: 6990,
    description: '方形強化玻璃桌面搭配鍍鉻金屬桌腳，俐落現代不佔視線。',
    image: COFFEE_TABLE_IMAGE_GLASS,
    details: [
      '方形強化玻璃',
      '鍍鉻金屬桌腳',
      '適合中型客廳',
    ],
    specs: [
      { label: '尺寸', value: '90x90 公分' },
      { label: '材質', value: '強化玻璃, 鍍鉻金屬' },
    ],
    stock: [{ location: '內湖店', status: 'in-stock' }],
    tags: ['玻璃', '客廳'],
    variantTags: ['鍍鉻色'],
    sizeDisplay: '大',
    material: '玻璃',
    aiReason: '方形玻璃台面，空間感通透',
  },
  {
    id: 'c5',
    name: 'KNARREVIK 邊桌',
    categoryId: 'coffee-tables',
    price: 299,
    description: '黑色大理石與透明玻璃層疊設計，圓形台面兼具質感與穩定。',
    image: COFFEE_TABLE_IMAGE_MARBLE,
    details: [
      '黑色大理石台面',
      '透明玻璃上層',
      '圓形小茶几造型',
    ],
    specs: [
      { label: '尺寸', value: 'Ø 55 公分' },
      { label: '材質', value: '大理石, 強化玻璃' },
    ],
    stock: [{ location: '內湖店', status: 'in-stock' }],
    tags: ['大理石', '邊桌'],
    variantTags: ['大理石黑'],
    sizeDisplay: '小',
    material: '大理石',
    aiReason: '大理石層疊設計，質感突出',
  },
  {
    id: 'c6',
    name: 'LÖVBACKEN 邊桌',
    categoryId: 'coffee-tables',
    price: 1290,
    description: '水磨石紋圓桌面搭配金色金屬桌腳，適合沙發旁點綴。',
    image: COFFEE_TABLE_IMAGE_TERRAZZO,
    details: [
      '水磨石紋桌面',
      '金色金屬桌腳',
      '圓形小巧造型',
    ],
    specs: [
      { label: '尺寸', value: 'Ø 45 公分' },
      { label: '材質', value: '水磨石, 金屬' },
    ],
    stock: [{ location: '內湖店', status: 'in-stock' }],
    tags: ['水磨石', '邊桌'],
    variantTags: ['水磨石'],
    sizeDisplay: '小',
    material: '水磨石',
    aiReason: '水磨石紋路，溫潤又有設計感',
  },
  {
    id: 'c8',
    name: 'STENKOL 邊桌',
    categoryId: 'coffee-tables',
    price: 799,
    description: '俐落現代邊桌，台面適合放置飲品或書籍，可搭配沙發使用。',
    image: COFFEE_TABLE_IMAGE_SIDE,
    details: [
      '簡約現代造型',
      '適合沙發旁',
      '輕巧好移動',
    ],
    specs: [
      { label: '尺寸', value: '40x40 公分' },
      { label: '材質', value: '金屬, 烤漆' },
    ],
    stock: [{ location: '內湖店', status: 'in-stock' }],
    tags: ['邊桌', '現代'],
    variantTags: ['黑灰'],
    sizeDisplay: '小',
    material: '金屬',
    aiReason: '簡約造型，適合小坪數空間',
  },
  {
    id: 's1',
    name: 'LANDSKRONA 三人沙發',
    categoryId: 'sofas',
    price: 24900,
    description: '簡約線條與舒適坐感，適合搭配木質茶几打造完整客廳。',
    image: '/images/living_room_inspiration_1779274975609.png',
    details: ['三人座設計', '可拆洗布套', '北歐休閒風格'],
    specs: [
      { label: '尺寸', value: '204x88x74 公分' },
      { label: '材質', value: '棉麻混紡布套' },
    ],
    stock: [{ location: '內湖店', status: 'in-stock' }],
    tags: ['客廳', '北歐風'],
    sizeDisplay: '三人',
    material: '布料',
    aiReason: '與木質茶几色調相近，客廳搭配首選',
  },
  {
    id: 'p1',
    name: 'POÄNG 扶手椅',
    categoryId: 'chairs',
    price: 2990,
    description: '經典彎木扶手椅，搭配高彈泡棉墊，舒適又耐看。',
    image: '/images/nordic_chair_white_bg_1779277500873.png',
    details: ['彎木框架', '可替換椅墊', '適合客廳閱讀角'],
    specs: [
      { label: '尺寸', value: '68x82x100 公分' },
      { label: '材質', value: '胡桃木、泡棉' },
    ],
    stock: [{ location: '內湖店', status: 'in-stock' }],
    tags: ['經典款', '客廳'],
    variantTags: ['胡桃木', '淺木紋'],
    sizeDisplay: '胡桃木',
    material: '胡桃木',
  },
  {
    id: 'w1',
    name: 'PAX 衣櫃組合',
    categoryId: 'storage',
    price: 12900,
    description: '模組化衣櫃設計，可依空間自由組合，整齊收納衣物。',
    image: '/images/wardrobe_white_closet.jpg',
    details: ['模組化設計', '大容量收納', '適合臥室與更衣室'],
    specs: [
      { label: '尺寸', value: '80–120 公分寬度可選' },
      { label: '材質', value: '纖維板、三聚氰胺貼面' },
    ],
    stock: [{ location: '內湖店', status: 'in-stock' }],
    tags: ['收納', '臥室'],
    variantTags: ['120cm', '80cm'],
    sizeDisplay: '120cm',
    material: '木質',
  },
  {
    id: 'l1',
    name: 'HEKTAR 吊燈',
    categoryId: 'lighting',
    price: 1490,
    description: '復古工業風吊燈，溫暖光線營造舒適居家氛圍。',
    image: '/images/lighting_pendant_lamp.jpg',
    details: ['工業復古風格', '適合客廳與餐廳', 'E27 燈座'],
    specs: [
      { label: '尺寸', value: 'Ø38 公分' },
      { label: '材質', value: '鋼鐵、環氧粉末塗料' },
    ],
    stock: [{ location: '內湖店', status: 'in-stock' }],
    tags: ['吊燈', '客廳'],
    variantTags: ['黑色', '白色'],
    sizeDisplay: '黑色',
    material: '金屬',
  },
];
